const env = import.meta.env

export const FIREBASE_SETTING = {
  API_KEY: env.VITE_FIREBASE_API_KEY,
  AUTH_DOMAIN: env.VITE_FIREBASE_AUTH_DOMAIN,
  PROJECT_ID: env.VITE_FIREBASE_PROJECT_ID,
  STORAGE_BUCKET: env.VITE_FIREBASE_STORAGE_BUCKET,
  MESSAGIN_SENDER_ID: env.VITE_FIREBASE_MESSAGIN_SENDER_ID,
  APP_ID: env.VITE_FIREBASE_APP_ID,
  MEASURATION_ID: env.VITE_FIREBASE_MEASURATION_ID
}